apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pkad
  name: pkad
spec:
  volumes:
    - name: cw3volume
      configMap:
        name: cw3
        items:
          - key: 30KB.txt
            path: 30KB.txt
  containers:
  - image: poznajkubernetes/pkad
    name: pkad
    resources: {}
    volumeMounts:
      - name: cw3volume
        mountPath: /etc/config        
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
