apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pkad
  name: pkad
spec:
  containers:
  - image: poznajkubernetes/pkad
    name: pkad
    resources: {}
    envFrom:
      - configMapRef:
          name: cw1
    env:
      - name: x
        value: 'from_pod_env'
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}