apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv-subpath
  labels:
    purpose: demo
spec:
  storageClassName: ""
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /d/k8s_vol/persistent_volume/retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc-subpath
spec:
  storageClassName: ""
  selector:
    matchLabels:
      purpose: demo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: web-pv-static-subpath
spec:
  initContainers:
    - image: ubuntu:latest
      name: setup
      volumeMounts:
        - name: workdir
          mountPath: /tempdir
      command: ["/bin/sh", "-c"]
      args:
        - echo "hello from subpath!!!" > /tempdir/index.html;
  containers:
    - image: nginx:1.17.6
      name: web
      ports:
        - containerPort: 80
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
  volumes:
    - name: workdir
      persistentVolumeClaim:
        claimName: demo-pvc-subpath