apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-rolling-update
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      name: pkad
  template:
    metadata:
      labels: 
        name: pkad
    spec:
      containers:
      - name: pkad
        image: poznajkubernetes/pkad:red
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080