apiVersion: v1
kind: Pod
metadata:
  name: pkdemoapp
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: file-secret
  containers:
  - image: krzyskowk/pk.demoapp:1.0.0
    name: pkdemoapp
    envFrom:
    - secretRef:
        name: literal-secret
        optional: false
    volumeMounts:
      - mountPath: /etc/secret
        name: secret-volume
  imagePullSecrets:
    - name: regcred
status: {}