# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: D:\k8s_vol\persistent_volume\local\node1
    containerPath: /files
- role: worker
  extraMounts:
  - hostPath: D:\k8s_vol\persistent_volume\local\node2
    containerPath: /files