apiVersion: v1
kind: ConfigMap
metadata:
  name: config1
data:
  udhcpd.conf: "hello from udhcpd.conf :wave:" 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config2
data:
  appsettings.json: "hello from appsettings.json :wave:"
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    command: ["sleep", "3000"]
    volumeMounts:
    - name: all-in-one
      mountPath: /allconfigs
    image: busybox
  volumes:
    - name: all-in-one
      projected:
        sources:
        - configMap:
            name: config1
        - configMap:
            name: config2