apiVersion: v1
kind: Service
metadata:
  name: nginx-0
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: nginx-0
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80