apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kuard-env-fieldref
  name: kuard-env-fieldref
spec:
  containers:
  - image: poznajkubernetes/kuard
    name: kuard-env
    resources: {}
    env:
      - name: 'X_POD_NAME'
        valueFrom:
          fieldRef:
            fieldPath: 'metadata.name'
      - name: 'X_IP_ADDRESS'
        valueFrom:
          fieldRef:
            fieldPath: 'status.hostIP'
      - name: 'X_NODE_NAME'
        valueFrom:
          fieldRef:
            fieldPath: 'spec.nodeName'
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
