apiVersion: v1
kind: Pod
metadata:
  name: helloapp
  labels:
    app: helloapp
spec:
  containers:
  - image: poznajkubernetes/helloapp:svc
    name: helloapp
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP