apiVersion: v1
kind: Pod
metadata:
  name: web-2
spec:
  containers:
    - image: nginx:1.17.6
      name: web-2
      ports:
        - containerPort: 80
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
  volumes:
    - name: workdir
      hostPath:
        path: /d/k8s_vol/host_path