apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollingupdate
spec:
  replicas: 6
  selector:
    matchLabels:
      app: helloapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - image: poznajkubernetes/helloapp:svc
        name: helloapp
        env:
        - name: version
          value: v6.0.0